// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjOWDx2Aczfw7ltkdgpxL5TgiGFeBcWMc',
    appId: '1:282083413168:web:f6e8a1e935b321f7eb3f75',
    messagingSenderId: '282083413168',
    projectId: 'to-do-app-dc97c',
    authDomain: 'to-do-app-dc97c.firebaseapp.com',
    storageBucket: 'to-do-app-dc97c.appspot.com',
    measurementId: 'G-G3EDPCXMZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCax9psZ_DSez2QwvLfnnInLTUYv1oDYJc',
    appId: '1:282083413168:android:97f574c892308481eb3f75',
    messagingSenderId: '282083413168',
    projectId: 'to-do-app-dc97c',
    storageBucket: 'to-do-app-dc97c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5eUERjVtebf8Vck4VMXDHIpT-fnJb1DY',
    appId: '1:282083413168:ios:328dc533cf12310aeb3f75',
    messagingSenderId: '282083413168',
    projectId: 'to-do-app-dc97c',
    storageBucket: 'to-do-app-dc97c.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5eUERjVtebf8Vck4VMXDHIpT-fnJb1DY',
    appId: '1:282083413168:ios:4864abbc17887136eb3f75',
    messagingSenderId: '282083413168',
    projectId: 'to-do-app-dc97c',
    storageBucket: 'to-do-app-dc97c.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
